# Generated by Django 2.0.7 on 2018-07-23 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MahilaPratinidhiFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='district/')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_district', to='core.District')),
            ],
        ),
        migrations.CreateModel(
            name='MahilaPratinidhiForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='कार्यक्रम')),
                ('age', models.IntegerField()),
                ('marital_status', models.CharField(max_length=300)),
                ('educational_qualification', models.CharField(max_length=300)),
                ('caste', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('contact_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('nirwachit_padh', models.CharField(max_length=300)),
                ('nirwachit_vdc_or_municipality_name', models.CharField(max_length=300)),
                ('party_name', models.CharField(max_length=300)),
                ('party_joined_date', models.DateField()),
                ('samlagna_sang_sastha_samuha', models.CharField(max_length=300)),
                ('nirwachit_chetra_pratiko_pratibadhata', models.TextField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='core.District')),
            ],
        ),
    ]
