# Generated by Django 2.0.7 on 2018-12-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='hlcit_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pratinidhishava',
            name='hlcit_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='provincemahilapratinidhiform',
            name='hlcit_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='hlcit_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
