# Generated by Django 2.0.7 on 2018-07-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='name',
            field=models.CharField(max_length=300, verbose_name='नाम'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='party_joined_date',
            field=models.CharField(max_length=300),
        ),
    ]
