# Generated by Django 2.0.7 on 2018-12-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181213_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataVizContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=50)),
                ('main_content', models.TextField()),
                ('content_variable', models.TextField()),
                ('content_province', models.TextField()),
                ('content_province_vs_federal_vs_national', models.TextField()),
                ('content_party', models.TextField()),
            ],
        ),
    ]
