# Generated by Django 2.0.7 on 2018-07-23 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180723_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahilapratinidhifile',
            name='district',
        ),
        migrations.DeleteModel(
            name='MahilaPratinidhiFile',
        ),
    ]
