# Generated by Django 2.0.7 on 2018-07-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180723_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='age',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='contact_number',
            field=models.CharField(max_length=300),
        ),
    ]
