# Generated by Django 2.0.7 on 2018-07-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180723_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='ठेगाना'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='age',
            field=models.CharField(max_length=300, verbose_name='उमेर'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='caste',
            field=models.CharField(blank=True, max_length=300, verbose_name='जातियता'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='contact_number',
            field=models.CharField(blank=True, max_length=300, verbose_name='सम्पर्क न.'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='core.District', verbose_name='जिल्ला'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='educational_qualification',
            field=models.CharField(blank=True, max_length=300, verbose_name='शैछिक योग्यता'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='इ-मेल'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='marital_status',
            field=models.CharField(blank=True, max_length=300, verbose_name='बैवाहिक स्थिथि'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='nirwachit_chetra_pratiko_pratibadhata',
            field=models.TextField(blank=True, verbose_name='निर्वाचित क्षेत्र प्रतिको प्रतिबध्धता'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='nirwachit_padh',
            field=models.CharField(blank=True, max_length=300, verbose_name='निर्वाचित पद'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='nirwachit_vdc_or_municipality_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='निर्वाचित गा.बि.स वा नगरपालिकाको नाम'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='party_joined_date',
            field=models.CharField(blank=True, max_length=300, verbose_name='पार्टीमा संलग्न भएको मिति'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='party_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='पार्टीको नाम'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='samlagna_sang_sastha_samuha',
            field=models.CharField(blank=True, max_length=300, verbose_name='संलग्न संग सस्था समूह'),
        ),
    ]
