# Generated by Django 2.0.7 on 2019-02-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_datavizcontent'),
        ('core', '0004_auto_20190102_1624'),
    ]

    operations = [
    ]
