# Generated by Django 2.0.7 on 2019-02-03 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20190128_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipalities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hlcit_code', models.CharField(max_length=50, unique=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='core.District')),
            ],
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='age',
            field=models.CharField(blank=True, max_length=300, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='age_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='age_ne_NP',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Age'),
        ),
    ]
