# Generated by Django 2.0.7 on 2019-02-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20190201_1408'),
        ('core', '0005_merge_20190128_0803'),
    ]

    operations = [
    ]
