# Generated by Django 2.0.7 on 2018-07-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180725_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='status',
            field=models.BooleanField(choices=[(True, 'Completed'), (False, 'Incomplete')], default=False),
        ),
    ]
