# Generated by Django 2.0.7 on 2019-02-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190203_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='updated_marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('विवाहित', 'विवाहित'), ('अविवाहित', 'अविवाहित')], max_length=300, verbose_name='बैवाहिक स्थिथि'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='updated_marital_status_en',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('विवाहित', 'विवाहित'), ('अविवाहित', 'अविवाहित')], max_length=300, null=True, verbose_name='बैवाहिक स्थिथि'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='updated_marital_status_ne_NP',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('विवाहित', 'विवाहित'), ('अविवाहित', 'अविवाहित')], max_length=300, null=True, verbose_name='बैवाहिक स्थिथि'),
        ),
    ]
