# Generated by Django 2.0.7 on 2019-02-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20190201_1423'),
        ('core', '0006_auto_20190203_0835'),
    ]

    operations = [
    ]
