# Generated by Django 2.0.7 on 2019-03-24 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20190205_0921'),
        ('core', '0007_auto_20190211_0510'),
    ]

    operations = [
    ]
