# Generated by Django 2.0.7 on 2018-07-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mahilapratinidhiform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='status',
            field=models.BooleanField(choices=[(True, 'पूरा'), (False, 'अपूर्ण')], default=False),
        ),
    ]
