# Generated by Django 2.0.7 on 2018-07-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180726_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='name',
            field=models.CharField(max_length=300, verbose_name='नाम'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='status',
            field=models.BooleanField(choices=[(True, 'पूर्ण'), (False, 'अपूर्ण')], default=False),
        ),
    ]
