# Generated by Django 2.0.7 on 2019-03-24 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_district_province'),
        ('core', '0008_merge_20190324_0730'),
    ]

    operations = [
    ]
