# Generated by Django 2.0.7 on 2019-05-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_district_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='नाम'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='name_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='नाम'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='name_ne_NP',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='नाम'),
        ),
        migrations.AlterField(
            model_name='pratinidhishava',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='pratinidhishava',
            name='date_of_birth_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='pratinidhishava',
            name='date_of_birth_ne_NP',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='pratinidhishava',
            name='english_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='pratinidhishava',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='बाबुको नाम'),
        ),
        migrations.AlterField(
            model_name='pratinidhishava',
            name='fathers_name_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='बाबुको नाम'),
        ),
        migrations.AlterField(
            model_name='pratinidhishava',
            name='fathers_name_ne_NP',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='बाबुको नाम'),
        ),
        migrations.AlterField(
            model_name='pratinidhishava',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='आमाको नाम'),
        ),
        migrations.AlterField(
            model_name='pratinidhishava',
            name='mothers_name_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='आमाको नाम'),
        ),
        migrations.AlterField(
            model_name='pratinidhishava',
            name='mothers_name_ne_NP',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='आमाको नाम'),
        ),
        migrations.AlterField(
            model_name='pratinidhishava',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='नाम'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='date_of_birth_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='date_of_birth_ne_NP',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='english_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='बाबुको नाम'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='fathers_name_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='बाबुको नाम'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='fathers_name_ne_NP',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='बाबुको नाम'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='आमाको नाम'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='mothers_name_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='आमाको नाम'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='mothers_name_ne_NP',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='आमाको नाम'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='नाम'),
        ),
        migrations.AlterField(
            model_name='rastriyashava',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='rastriyashava',
            name='date_of_birth_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='rastriyashava',
            name='date_of_birth_ne_NP',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='rastriyashava',
            name='english_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='rastriyashava',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='बाबुको नाम'),
        ),
        migrations.AlterField(
            model_name='rastriyashava',
            name='fathers_name_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='बाबुको नाम'),
        ),
        migrations.AlterField(
            model_name='rastriyashava',
            name='fathers_name_ne_NP',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='बाबुको नाम'),
        ),
        migrations.AlterField(
            model_name='rastriyashava',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='आमाको नाम'),
        ),
        migrations.AlterField(
            model_name='rastriyashava',
            name='mothers_name_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='आमाको नाम'),
        ),
        migrations.AlterField(
            model_name='rastriyashava',
            name='mothers_name_ne_NP',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='आमाको नाम'),
        ),
        migrations.AlterField(
            model_name='rastriyashava',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='नाम'),
        ),
    ]
