# Generated by Django 2.0.7 on 2018-08-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180726_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='updated_marital_status',
            field=models.CharField(blank=True, choices=[('cljjflxt', 'अविवाहित'), ('ljjflxt', 'विवाहित'), ('Psn', 'एकल'), ('cGo', 'अन्य')], max_length=300, verbose_name='बैवाहिक स्थिथि'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile/', verbose_name='फोटो'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='status',
            field=models.BooleanField(choices=[(True, 'पूर्ण'), (False, 'अपूर्ण')], default=False, verbose_name='स्थिति'),
        ),
    ]
