# Generated by Django 2.0.7 on 2018-08-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180801_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='updated_caste',
            field=models.CharField(blank=True, choices=[('blnt', 'दलित'), ('cflbaf;L÷hghftL', 'आदिबासी / जनजाती'), ('v; cfo{', 'खस आर्य'), ('dw];L ', 'मधेसी'), ('yf?', 'थारु'), ('d"l:nd', 'मुस्लिम'), ('cGo', 'अन्य')], default='blnt', max_length=300, verbose_name='जातियता'),
        ),
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='updated_educational_qualification',
            field=models.CharField(blank=True, choices=[('lg/If/', 'निरक्षर'), (';fIf/', 'साक्षर'), ('P;=Pn=;L= ', 'एस.एल.सी.'), ('!) @ jf ;f] ;/x', '१० + २ वा सो सरह'), (':gfts', 'स्नातक'), (':gfsf]]t/', 'स्नाकोतर'), ('lk=Pr=8L=', 'पि.एच.डी')], default='lg/If/', max_length=300, verbose_name='शैछिक योग्यता'),
        ),
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='updated_marital_status',
            field=models.CharField(blank=True, choices=[('cljjflxt', 'अविवाहित'), ('ljjflxt', 'विवाहित'), ('Psn', 'एकल'), ('cGo', 'अन्य')], default='cljjflxt', max_length=300, verbose_name='बैवाहिक स्थिथि'),
        ),
    ]
