# Generated by Django 2.0.7 on 2019-05-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20190324_0841'),
        ('core', '0010_auto_20190523_0712'),
    ]

    operations = [
    ]
