# Generated by Django 2.0.7 on 2018-08-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180801_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='elected_women',
            field=models.IntegerField(default=0),
        ),
    ]
