# Generated by Django 2.0.7 on 2018-09-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_province_provincemahilapratinidhiform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='provinceProfile/', verbose_name='फोटो'),
        ),
    ]
