# Generated by Django 2.0.7 on 2018-10-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20181003_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincemahilapratinidhiform',
            name='updated_aaja_vanda_agadi_chunab_ladnu_vayeko_chha',
            field=models.CharField(choices=[('समानुपातिक', 'समानुपातिक'), ('छैन', 'छैन'), ('छ', 'छ')], default=1, max_length=300, verbose_name='आज भन्दा अघि चुनाब लड्नुभएको छ?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provincemahilapratinidhiform',
            name='updated_caste',
            field=models.CharField(blank=True, choices=[('blnt', 'दलित'), ('cflbaf;L÷hghftL', 'आदिबासी / जनजाती'), ('v; cfo{', 'खस आर्य'), ('dw];L ', 'मधेसी'), ('yf?', 'थारु'), ('d"l:nd', 'मुस्लिम'), ('cGo', 'अन्य')], max_length=300, verbose_name='जातियता'),
        ),
        migrations.AddField(
            model_name='provincemahilapratinidhiform',
            name='updated_marital_status',
            field=models.CharField(blank=True, choices=[('cljjflxt', 'अविवाहित'), ('ljjflxt', 'विवाहित'), ('Psn', 'एकल'), ('cGo', 'अन्य')], max_length=300, null=True, verbose_name='बैवाहिक स्थिथि'),
        ),
        migrations.AddField(
            model_name='provincemahilapratinidhiform',
            name='updated_nirwachit_padh',
            field=models.CharField(blank=True, choices=[('सांसद - प्रदेशसभा', 'सांसद - प्रदेशसभा')], max_length=300, verbose_name='निर्वाचित पद'),
        ),
        migrations.AddField(
            model_name='provincemahilapratinidhiform',
            name='updated_nirwachit_prakriya',
            field=models.CharField(blank=True, choices=[('समानुपातिक', 'समानुपातिक'), ('प्रतक्ष्य', 'प्रतक्ष्य')], max_length=300, verbose_name='निर्वाचित प्रक्रिया'),
        ),
        migrations.AddField(
            model_name='provincemahilapratinidhiform',
            name='updated_nirwachit_vayeko_chhetra_aafno_thegana',
            field=models.CharField(blank=True, choices=[('हो', 'हो'), ('होइन', 'होइन')], max_length=300, null=True, verbose_name='निर्वाचित भएको क्षेत्र आफ्नो अस्थायी/ स्थायी ठेगाना भन्दा फरक'),
        ),
        migrations.AddField(
            model_name='provincemahilapratinidhiform',
            name='updated_pichidiyeko_chhetra_ho_hoina',
            field=models.CharField(blank=True, choices=[('हो', 'हो'), ('होइन', 'होइन')], max_length=300, verbose_name='पिछडिएको क्षेत्र हो कि होइन'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='aaja_vanda_agadi_chunab_ladnu_vayeko_chha',
            field=models.CharField(max_length=300, verbose_name='आज भन्दा अघि चुनाब लड्नुभएको छ?'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='caste',
            field=models.CharField(max_length=300, verbose_name='जातियता'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='nirwachit_padh',
            field=models.CharField(blank=True, max_length=300, verbose_name='निर्वाचित पद'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='nirwachit_prakriya',
            field=models.CharField(blank=True, max_length=300, verbose_name='निर्वाचित प्रक्रिया'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='nirwachit_vayeko_chhetra_aafno_thegana',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='निर्वाचित भएको क्षेत्र आफ्नो अस्थायी/ स्थायी ठेगाना भन्दा फरक'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='pichidiyeko_chhetra_ho_hoina',
            field=models.CharField(blank=True, max_length=300, verbose_name='पिछडिएको क्षेत्र हो कि होइन'),
        ),
    ]
