# Generated by Django 2.0.7 on 2018-10-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20181003_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='marital_status',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='बैवाहिक स्थिथि'),
        ),
    ]
