# Generated by Django 2.0.7 on 2018-10-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20181003_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='updated_aaja_vanda_agadi_chunab_ladnu_vayeko_chha',
            field=models.CharField(blank=True, choices=[('समानुपातिक', 'समानुपातिक'), ('छैन', 'छैन'), ('छ', 'छ')], max_length=300, null=True, verbose_name='आज भन्दा अघि चुनाब लड्नुभएको छ?'),
        ),
    ]
