# Generated by Django 2.0.7 on 2018-10-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_provincemahilapratinidhiform_updated_mother_tongue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='updated_mother_tongue',
            field=models.CharField(blank=True, choices=[('नेपाली', 'नेपाली'), ('मगर खामस्तानाकोतरराजनीति शास्त्र', 'मगर खामस्तानाकोतरराजनीति शास्त्र'), ('नेवारी', 'नेवारी'), ('नेपाल भाषा', 'नेपाल भाषा'), ('तामाङ', 'तामाङ')], max_length=300, verbose_name='मातृभाषा'),
        ),
    ]
