# Generated by Django 2.0.7 on 2018-10-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20181003_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='updated_educational_qualification',
            field=models.CharField(blank=True, choices=[('lg/If/', 'निरक्षर'), (';fIf/', 'साक्षर'), ('P;=Pn=;L= ', 'एस.एल.सी.'), ('!) @ jf ;f] ;/x', '१० + २ वा सो सरह'), (':gfts', 'स्नातक'), (':gfsf]]t/', 'स्नाकोतर'), ('lk=Pr=8L=', 'पि.एच.डी')], max_length=300, verbose_name='औपचारिक शैक्षिक योग्यता'),
        ),
    ]
