# Generated by Django 2.0.7 on 2018-10-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20181003_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='aaja_vanda_agadi_chunab_ladnu_vayeko_chha',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='आज भन्दा अघि चुनाब लड्नुभएको छ?'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='caste',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='जातियता'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='educational_qualification',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='औपचारिक शैक्षिक योग्यता'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='इ-मेल'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='मातृभाषा'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='nirwachit_chetra_pratiko_pratibadhata',
            field=models.TextField(blank=True, null=True, verbose_name='निर्वाचित क्षेत्र प्रतिको प्रतिबध्धता'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='nirwachit_prakriya',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='निर्वाचित प्रक्रिया'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='party_joined_date',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='पार्टीमा संलग्न भएको मिति'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ठेगाना(स्थायी): जिल्ला'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='permanent_gapa_napa',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='गाउँपालिका/नगरपालिका/उप-महानगरपालिका/महानगरपालिका'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='pichidiyeko_chhetra_ho_hoina',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='पिछडिएको क्षेत्र हो कि होइन'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='subject',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='बिषय'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='updated_caste',
            field=models.CharField(blank=True, choices=[('blnt', 'दलित'), ('cflbaf;L÷hghftL', 'आदिबासी / जनजाती'), ('v; cfo{', 'खस आर्य'), ('dw];L ', 'मधेसी'), ('yf?', 'थारु'), ('d"l:nd', 'मुस्लिम'), ('cGo', 'अन्य')], max_length=300, null=True, verbose_name='जातियता'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='updated_educational_qualification',
            field=models.CharField(blank=True, choices=[('lg/If/', 'निरक्षर'), (';fIf/', 'साक्षर'), ('P;=Pn=;L= ', 'एस.एल.सी.'), ('!) @ jf ;f] ;/x', '१० + २ वा सो सरह'), (':gfts', 'स्नातक'), (':gfsf]]t/', 'स्नाकोतर'), ('lk=Pr=8L=', 'पि.एच.डी')], max_length=300, null=True, verbose_name='औपचारिक शैक्षिक योग्यता'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='updated_mother_tongue',
            field=models.CharField(blank=True, choices=[('नेपाली', 'नेपाली'), ('मगर खामस्तानाकोतरराजनीति शास्त्र', 'मगर खामस्तानाकोतरराजनीति शास्त्र'), ('नेवारी', 'नेवारी'), ('नेपाल भाषा', 'नेपाल भाषा'), ('तामाङ', 'तामाङ')], max_length=300, null=True, verbose_name='मातृभाषा'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='updated_nirwachit_padh',
            field=models.CharField(blank=True, choices=[('सांसद - प्रदेशसभा', 'सांसद - प्रदेशसभा')], max_length=300, null=True, verbose_name='निर्वाचित पद'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='updated_nirwachit_prakriya',
            field=models.CharField(blank=True, choices=[('समानुपातिक', 'समानुपातिक'), ('प्रतक्ष्य', 'प्रतक्ष्य')], max_length=300, null=True, verbose_name='निर्वाचित प्रक्रिया'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='updated_pichidiyeko_chhetra_ho_hoina',
            field=models.CharField(blank=True, choices=[('हो', 'हो'), ('होइन', 'होइन')], max_length=300, null=True, verbose_name='पिछडिएको क्षेत्र हो कि होइन'),
        ),
    ]
