# Generated by Django 2.0.7 on 2018-11-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_pratinidhishava_rastriyashava'),
    ]

    operations = [
        migrations.AddField(
            model_name='pratinidhishava',
            name='age',
            field=models.CharField(blank=True, max_length=300, verbose_name='उमेर'),
        ),
        migrations.AddField(
            model_name='provincemahilapratinidhiform',
            name='age',
            field=models.CharField(blank=True, max_length=300, verbose_name='उमेर'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='age',
            field=models.CharField(blank=True, max_length=300, verbose_name='उमेर'),
        ),
    ]
