# Generated by Django 2.0.7 on 2018-11-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20181120_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='pratinidhishava',
            name='samitima_vumika',
            field=models.CharField(blank=True, max_length=300, verbose_name=''),
        ),
        migrations.AddField(
            model_name='pratinidhishava',
            name='samlagna_samsadiya_samiti',
            field=models.CharField(blank=True, max_length=300, verbose_name=''),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='samitima_vumika',
            field=models.CharField(blank=True, max_length=300, verbose_name=''),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='samlagna_samsadiya_samiti',
            field=models.CharField(blank=True, max_length=300, verbose_name=''),
        ),
    ]
