# Generated by Django 2.0.7 on 2018-11-16 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20181116_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahilapratinidhiform',
            name='status_en',
        ),
    ]
