# Generated by Django 2.0.7 on 2018-11-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20181120_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rastriyashava',
            name='samitima_vumika',
            field=models.CharField(blank=True, max_length=300, verbose_name='समितिमा पद'),
        ),
        migrations.AlterField(
            model_name='rastriyashava',
            name='samlagna_samsadiya_samiti',
            field=models.CharField(blank=True, max_length=300, verbose_name='संलग्न समिति'),
        ),
    ]
