# Generated by Django 2.0.7 on 2018-11-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20181120_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratinidhishava',
            name='samitima_vumika',
            field=models.CharField(blank=True, max_length=300, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pratinidhishava',
            name='samlagna_samsadiya_samiti',
            field=models.CharField(blank=True, max_length=300, verbose_name=''),
        ),
    ]
