# Generated by Django 2.0.7 on 2018-11-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_backgroundimage'),
        ('core', '0030_auto_20181120_1443'),
    ]

    operations = [
    ]
