# Generated by Django 2.0.7 on 2018-11-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_merge_20181120_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahilapratinidhiform',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='mahilapratinidhiform',
            name='age_en',
        ),
        migrations.RemoveField(
            model_name='mahilapratinidhiform',
            name='caste_en',
        ),
        migrations.RemoveField(
            model_name='mahilapratinidhiform',
            name='contact_number_en',
        ),
        migrations.RemoveField(
            model_name='mahilapratinidhiform',
            name='educational_qualification_en',
        ),
        migrations.RemoveField(
            model_name='mahilapratinidhiform',
            name='email_en',
        ),
        migrations.RemoveField(
            model_name='mahilapratinidhiform',
            name='marital_status_en',
        ),
        migrations.RemoveField(
            model_name='mahilapratinidhiform',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='mahilapratinidhiform',
            name='nirwachit_chetra_pratiko_pratibadhata_en',
        ),
        migrations.RemoveField(
            model_name='mahilapratinidhiform',
            name='nirwachit_padh_en',
        ),
        migrations.RemoveField(
            model_name='mahilapratinidhiform',
            name='nirwachit_vdc_or_municipality_name_en',
        ),
        migrations.RemoveField(
            model_name='mahilapratinidhiform',
            name='party_joined_date_en',
        ),
        migrations.RemoveField(
            model_name='mahilapratinidhiform',
            name='party_name_en',
        ),
        migrations.RemoveField(
            model_name='mahilapratinidhiform',
            name='samlagna_sang_sastha_samuha_en',
        ),
        migrations.RemoveField(
            model_name='mahilapratinidhiform',
            name='updated_caste_en',
        ),
        migrations.RemoveField(
            model_name='mahilapratinidhiform',
            name='updated_educational_qualification_en',
        ),
        migrations.RemoveField(
            model_name='mahilapratinidhiform',
            name='updated_marital_status_en',
        ),
    ]
