# Generated by Django 2.0.7 on 2018-11-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20181120_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pratinidhishava',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provincemahilapratinidhiform',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
