# Generated by Django 2.0.7 on 2018-11-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20181120_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratinidhishava',
            name='pramukh_jimmewari',
            field=models.CharField(blank=True, max_length=500, verbose_name='प्रमुख जिम्मेवारी '),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='pramukh_jimmewari',
            field=models.CharField(blank=True, max_length=500, verbose_name='प्रमुख जिम्मेवारी '),
        ),
        migrations.AlterField(
            model_name='rastriyashava',
            name='pramukh_jimmewari',
            field=models.CharField(blank=True, max_length=500, verbose_name='प्रमुख जिम्मेवारी '),
        ),
    ]
