# Generated by Django 2.0.7 on 2018-11-22 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20181121_0540'),
        ('core', '0033_auto_20181121_1045'),
    ]

    operations = [
    ]
