# Generated by Django 2.0.7 on 2018-11-22 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0034_merge_20181122_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='newsOf',
        ),
        migrations.AddField(
            model_name='news',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='news',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
