# Generated by Django 2.0.7 on 2018-11-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20181122_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='address_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ठेगाना'),
        ),
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='age_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='उमेर'),
        ),
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='caste_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='जातियता'),
        ),
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='contact_number_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='सम्पर्क न.'),
        ),
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='educational_qualification_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='शैछिक योग्यता'),
        ),
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='email_en',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='इ-मेल'),
        ),
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='marital_status_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='बैवाहिक स्थिथि'),
        ),
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='नाम'),
        ),
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='nirwachit_chetra_pratiko_pratibadhata_en',
            field=models.TextField(blank=True, null=True, verbose_name='निर्वाचित क्षेत्र प्रतिको प्रतिबध्धता'),
        ),
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='nirwachit_padh_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='निर्वाचित पद'),
        ),
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='nirwachit_vdc_or_municipality_name_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='निर्वाचित गा.बि.स वा नगरपालिकाको नाम'),
        ),
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='party_joined_date_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='पार्टीमा संलग्न भएको मिति'),
        ),
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='party_name_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='पार्टीको नाम'),
        ),
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='samlagna_sang_sastha_samuha_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='संलग्न संग सस्था समूह'),
        ),
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='updated_caste_en',
            field=models.CharField(blank=True, choices=[('blnt', 'दलित'), ('cflbaf;L÷hghftL', 'आदिबासी / जनजाती'), ('v; cfo{', 'खस आर्य'), ('dw];L ', 'मधेसी'), ('yf?', 'थारु'), ('d"l:nd', 'मुस्लिम'), ('cGo', 'अन्य')], max_length=300, null=True, verbose_name='जातियता'),
        ),
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='updated_educational_qualification_en',
            field=models.CharField(blank=True, choices=[('lg/If/', 'निरक्षर'), (';fIf/', 'साक्षर'), ('P;=Pn=;L= ', 'एस.एल.सी.'), ('!) @ jf ;f] ;/x', '१० + २ वा सो सरह'), (':gfts', 'स्नातक'), (':gfsf]]t/', 'स्नाकोतर'), ('lk=Pr=8L=', 'पि.एच.डी')], max_length=300, null=True, verbose_name='शैछिक योग्यता'),
        ),
        migrations.AddField(
            model_name='mahilapratinidhiform',
            name='updated_marital_status_en',
            field=models.CharField(blank=True, choices=[('cljjflxt', 'अविवाहित'), ('ljjflxt', 'विवाहित'), ('Psn', 'एकल'), ('cGo', 'अन्य')], max_length=300, null=True, verbose_name='बैवाहिक स्थिथि'),
        ),
    ]
