# Generated by Django 2.0.7 on 2018-11-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20181122_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='story_headline',
            field=models.TextField(blank=True),
        ),
    ]
