# Generated by Django 2.0.7 on 2018-11-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20181122_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='rastriyashava',
            name='aaja_vanda_agadi_chunab_ladnu_vayeko_chha_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='आज भन्दा अघि चुनाब लड्नुभएको छ?'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='caste_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='जातियता'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='contact_number_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='सम्पर्क न.'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='date_of_birth_en',
            field=models.CharField(max_length=300, null=True, verbose_name='जन्ममिती'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='educational_qualification_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='औपचारिक शैक्षिक योग्यता'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='email_en',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='इ-मेल'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='fathers_name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='बाबुको नाम'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='husbands_name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='श्रीमानको नाम'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='marital_status_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='बैवाहिक स्थिथि'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='mobile_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='मोवाइल'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='mother_tongue_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='मातृभाषा'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='mothers_name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='आमाको नाम'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='nirwachit_chetra_pratiko_pratibadhata_en',
            field=models.TextField(blank=True, null=True, verbose_name='निर्वाचित क्षेत्र प्रतिको प्रतिबध्धता'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='nirwachit_chhetrako_bibaran_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='निर्वाचित क्षेत्रको विवरण'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='nirwachit_padh_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='निर्वाचित पद'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='nirwachit_prakriya_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='निर्वाचित प्रक्रिया'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='nirwachit_vayeko_chhetra_aafno_thegana_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='निर्वाचित भएको क्षेत्र आफ्नो अस्थायी/ स्थायी ठेगाना भन्दा फरक'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='party_joined_date_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='पार्टीमा संलग्न भएको मिति'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='party_name_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='पार्टीको विवरण: पार्टीको नाम'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='permanent_address_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ठेगाना(स्थायी): जिल्ला'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='permanent_gapa_napa_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='गाउँपालिका/नगरपालिका/उप-महानगरपालिका/महानगरपालिका'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='permanent_tole_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='टोल'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='permanent_ward_no_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='वडा नं'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='pichidiyeko_chhetra_ho_hoina_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='पिछडिएको क्षेत्र हो कि होइन'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='pramukh_jimmewari_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='प्रमुख जिम्मेवारी '),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='prapta_maat_sankhya_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='प्राप्त मत संख्या'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='samitima_vumika_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='समितिमा पद'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='samlagna_samsadiya_samiti_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='संलग्न समिति'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='samlagna_sang_sastha_samuha_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='सलग्न संघ, सस्था , समूह'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='social_networking_medium_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='सामाजिक सन्जालका माध्यम(छ भने):'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='subject_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='बिषय'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='temporary_address_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ठेगाना(अस्थायी): जिल्ला'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='temporary_gapa_napa_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='गाउँपालिका/नगरपालिका/उप-महानगरपालिका/महानगरपालिका'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='temporary_tole_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='टोल'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='temporary_ward_no_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='वडा नं'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='updated_aaja_vanda_agadi_chunab_ladnu_vayeko_chha_en',
            field=models.CharField(blank=True, choices=[('समानुपातिक', 'समानुपातिक'), ('छैन', 'छैन'), ('छ', 'छ')], max_length=300, null=True, verbose_name='आज भन्दा अघि चुनाब लड्नुभएको छ?'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='updated_caste_en',
            field=models.CharField(blank=True, choices=[('blnt', 'दलित'), ('cflbaf;L÷hghftL', 'आदिबासी / जनजाती'), ('v; cfo{', 'खस आर्य'), ('dw];L ', 'मधेसी'), ('yf?', 'थारु'), ('d"l:nd', 'मुस्लिम'), ('cGo', 'अन्य')], max_length=300, null=True, verbose_name='जातियता'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='updated_educational_qualification_en',
            field=models.CharField(blank=True, choices=[('lg/If/', 'निरक्षर'), (';fIf/', 'साक्षर'), ('P;=Pn=;L= ', 'एस.एल.सी.'), ('!) @ jf ;f] ;/x', '१० + २ वा सो सरह'), (':gfts', 'स्नातक'), (':gfsf]]t/', 'स्नाकोतर'), ('lk=Pr=8L=', 'पि.एच.डी')], max_length=300, null=True, verbose_name='औपचारिक शैक्षिक योग्यता'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='updated_marital_status_en',
            field=models.CharField(blank=True, choices=[('cljjflxt', 'अविवाहित'), ('ljjflxt', 'विवाहित'), ('Psn', 'एकल'), ('cGo', 'अन्य')], max_length=300, null=True, verbose_name='बैवाहिक स्थिथि'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='updated_mother_tongue_en',
            field=models.CharField(blank=True, choices=[('नेपाली', 'नेपाली'), ('मगर खामस्तानाकोतरराजनीति शास्त्र', 'मगर खामस्तानाकोतरराजनीति शास्त्र'), ('नेवारी', 'नेवारी'), ('नेपाल भाषा', 'नेपाल भाषा'), ('तामाङ', 'तामाङ')], max_length=300, null=True, verbose_name='मातृभाषा'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='updated_nirwachit_padh_en',
            field=models.CharField(blank=True, choices=[('सांसद - प्रदेशसभा', 'सांसद - प्रदेशसभा')], max_length=300, null=True, verbose_name='निर्वाचित पद'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='updated_nirwachit_prakriya_en',
            field=models.CharField(blank=True, choices=[('समानुपातिक', 'समानुपातिक'), ('प्रतक्ष्य', 'प्रतक्ष्य')], max_length=300, null=True, verbose_name='निर्वाचित प्रक्रिया'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='updated_nirwachit_vayeko_chhetra_aafno_thegana_en',
            field=models.CharField(blank=True, choices=[('हो', 'हो'), ('होइन', 'होइन')], max_length=300, null=True, verbose_name='निर्वाचित भएको क्षेत्र आफ्नो अस्थायी/ स्थायी ठेगाना भन्दा फरक'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='updated_pichidiyeko_chhetra_ho_hoina_en',
            field=models.CharField(blank=True, choices=[('हो', 'हो'), ('होइन', 'होइन')], max_length=300, null=True, verbose_name='पिछडिएको क्षेत्र हो कि होइन'),
        ),
    ]
