# Generated by Django 2.0.7 on 2018-11-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_news_story_headline'),
        ('core', '0038_auto_20181122_1454'),
    ]

    operations = [
    ]
