# Generated by Django 2.0.7 on 2018-11-26 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_merge_20181123_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='pratinidhishava',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Province', verbose_name='प्रदेश'),
        ),
        migrations.AddField(
            model_name='rastriyashava',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Province', verbose_name='प्रदेश'),
        ),
    ]
