# Generated by Django 2.0.7 on 2018-12-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_mahilapratinidhiform_province'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'get_latest_by': ['date']},
        ),
    ]
