# Generated by Django 2.0.7 on 2018-12-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_credit',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
