# Generated by Django 2.0.7 on 2018-12-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20181211_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratinidhishava',
            name='date_of_birth',
            field=models.DateField(verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='pratinidhishava',
            name='date_of_birth_en',
            field=models.DateField(null=True, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='pratinidhishava',
            name='date_of_birth_ne_NP',
            field=models.DateField(null=True, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='date_of_birth',
            field=models.DateField(verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='date_of_birth_en',
            field=models.DateField(null=True, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='date_of_birth_ne_NP',
            field=models.DateField(null=True, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='rastriyashava',
            name='date_of_birth',
            field=models.DateField(verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='rastriyashava',
            name='date_of_birth_en',
            field=models.DateField(null=True, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='rastriyashava',
            name='date_of_birth_ne_NP',
            field=models.DateField(null=True, verbose_name='जन्ममिती'),
        ),
    ]
