# Generated by Django 2.0.7 on 2018-12-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20181212_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratinidhishava',
            name='date_of_birth',
            field=models.CharField(max_length=300, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='pratinidhishava',
            name='date_of_birth_en',
            field=models.CharField(max_length=300, null=True, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='pratinidhishava',
            name='date_of_birth_ne_NP',
            field=models.CharField(max_length=300, null=True, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='date_of_birth',
            field=models.CharField(max_length=300, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='date_of_birth_en',
            field=models.CharField(max_length=300, null=True, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='provincemahilapratinidhiform',
            name='date_of_birth_ne_NP',
            field=models.CharField(max_length=300, null=True, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='rastriyashava',
            name='date_of_birth',
            field=models.CharField(max_length=300, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='rastriyashava',
            name='date_of_birth_en',
            field=models.CharField(max_length=300, null=True, verbose_name='जन्ममिती'),
        ),
        migrations.AlterField(
            model_name='rastriyashava',
            name='date_of_birth_ne_NP',
            field=models.CharField(max_length=300, null=True, verbose_name='जन्ममिती'),
        ),
    ]
