# Generated by Django 2.0.7 on 2018-12-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_district_province'),
        ('core', '0048_auto_20181212_0607'),
    ]

    operations = [
    ]
