# Generated by Django 2.0.7 on 2018-12-12 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_merge_20181212_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahilapratinidhiform',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mahilapratinidhiform', to='core.Province', verbose_name='प्रदेश'),
        ),
    ]
