# Generated by Django 2.0.7 on 2018-12-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20181212_0859'),
        ('core', '0045_auto_20181211_1003'),
    ]

    operations = [
    ]
